version: '3'
services:
    gps-service:
        build: .
        working_dir: /usr/src/app
        depends_on:
            - mongo
        ports:
            - "8080:8080"
    mongo:
        image: "mongo"
        ports:
        - "27017:27017"
        expose:
        - 27017
