version: '3'
services:
    gps-service:
        build: .
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        depends_on:
            - mongo
        ports:
            - "4040:4040"
    mongo:
        image: "mongo"
        ports:
        - "27017:27017"
        expose:
        - 27017
