version: '3'
services:
    express-typescript:
        build: .
        container_name: 'my-express-typescript'
        volumes:
            - .:/usr/src/app/
        working_dir: /usr/src/app
        environment:
            - MONGOOSE_URL=mongodb://mongo:27017/typescript_mongoose
        command: sh -c "npm install && npm run dev"
        depends_on:
            - mongo
        ports:
            - "4040:4040"
            - "5550:5550"
    mongo:
        image: "mongo"
        ports:
        - "27017:27017"
        expose:
        - 27017
